// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Person.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PersonRoot

@implementation PersonRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - PersonRoot_FileDescriptor

static GPBFileDescriptor *PersonRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"csdnblog"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - PBUser

@implementation PBUser

@dynamic hasUserId, userId;
@dynamic hasNick, nick;
@dynamic hasAvatar, avatar;
@dynamic hasPassword, password;
@dynamic hasEmail, email;
@dynamic hasMobile, mobile;
@dynamic hasQqOpenId, qqOpenId;
@dynamic hasSinaId, sinaId;
@dynamic hasWeixinId, weixinId;

typedef struct PBUser__storage_ {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *nick;
  NSString *avatar;
  NSString *password;
  NSString *email;
  NSString *mobile;
  NSString *qqOpenId;
  NSString *sinaId;
  NSString *weixinId;
} PBUser__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = PBUser_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PBUser__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "nick",
        .dataTypeSpecific.className = NULL,
        .number = PBUser_FieldNumber_Nick,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PBUser__storage_, nick),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "avatar",
        .dataTypeSpecific.className = NULL,
        .number = PBUser_FieldNumber_Avatar,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PBUser__storage_, avatar),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "password",
        .dataTypeSpecific.className = NULL,
        .number = PBUser_FieldNumber_Password,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PBUser__storage_, password),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "email",
        .dataTypeSpecific.className = NULL,
        .number = PBUser_FieldNumber_Email,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PBUser__storage_, email),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "mobile",
        .dataTypeSpecific.className = NULL,
        .number = PBUser_FieldNumber_Mobile,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PBUser__storage_, mobile),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "qqOpenId",
        .dataTypeSpecific.className = NULL,
        .number = PBUser_FieldNumber_QqOpenId,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PBUser__storage_, qqOpenId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sinaId",
        .dataTypeSpecific.className = NULL,
        .number = PBUser_FieldNumber_SinaId,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PBUser__storage_, sinaId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "weixinId",
        .dataTypeSpecific.className = NULL,
        .number = PBUser_FieldNumber_WeixinId,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PBUser__storage_, weixinId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PBUser class]
                                     rootClass:[PersonRoot class]
                                          file:PersonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PBUser__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\001\006\000\n\010\000\013\006\000\014\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
